# packages in environment at /home/zorino/packages/dev/anaconda3/envs/ray:
#
biopython                 1.68                np112py36_0  
CacheControl              0.12.2                    <pip>
cycler                    0.10.0                    <pip>
decorator                 4.0.11                    <pip>
ete3                      3.0.0b35                  <pip>
ipython                   5.3.0                     <pip>
ipython-genutils          0.2.0                     <pip>
libgfortran               3.0.0                         1  
lockfile                  0.12.2                    <pip>
matplotlib                2.0.0                     <pip>
mkl                       2017.0.1                      0  
msgpack-python            0.4.8                     <pip>
natsort                   5.0.2                     <pip>
nose                      1.3.7                     <pip>
numpy                     1.12.1                   py36_0  
openssl                   1.0.2k                        1  
pandas                    0.19.2              np112py36_1  
pexpect                   4.2.1                     <pip>
pickleshare               0.7.4                     <pip>
pip                       9.0.1                    py36_1  
prompt-toolkit            1.0.14                    <pip>
ptyprocess                0.5.1                     <pip>
pyani                     0.2.3                     <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.1.4                    py36_0  
python                    3.6.1                         0  
python-dateutil           2.6.0                    py36_0  
pytz                      2017.2                   py36_0  
Pyvolve                   0.8.4                     <pip>
readline                  6.2                           2  
requests                  2.13.0                    <pip>
scikit-bio                0.5.1                     <pip>
scipy                     0.19.0              np112py36_0  
seaborn                   0.7.1                     <pip>
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                     <pip>
six                       1.10.0                   py36_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
traitlets                 4.3.2                     <pip>
wcwidth                   0.1.7                     <pip>
wheel                     0.29.0                   py36_0  
xz                        5.2.2                         1  
zlib                      1.2.8                         3  
